CREATE TABLE IF NOT EXISTS `datalake-vanti.integracion_suplos.certificados`(
  SOCIEDAD STRING OPTIONS(description = "")
  , CONTADOR NUMERIC OPTIONS(description = "")
  , 0GL_ACCOUNT STRING OPTIONS(description = "")
  , 0COMP_CODE STRING OPTIONS(description = "")
  , ZXREF2 STRING OPTIONS(description = "")
  , DOCUMENTO STRING OPTIONS(description = "")
  , EJERCICIO NUMERIC OPTIONS(description = "")
  , PERIODO NUMERIC OPTIONS(description = "")
  , POSICION NUMERIC OPTIONS(description = "")
  , TIPO_RETENCION STRING OPTIONS(description = "")
  , IND_RETENCION STRING OPTIONS(description = "")
  , BASE NUMERIC OPTIONS(description = "")
  , IMP_RETENCION NUMERIC OPTIONS(description = "")
  , IMP_EXEN_IMP NUMERIC OPTIONS(description = "")
  , XREF1 STRING OPTIONS(description = "")
  , XREF3 STRING OPTIONS(description = "")
  , CLASE_DOCUMENTO STRING OPTIONS(description = "")
  , FECHA_DOC DATE OPTIONS(description = "")
  , FECHA_CONT DATE OPTIONS(description = "")
  , MONEDA_LOCAL STRING OPTIONS(description = "")
  , VALOR_MONEDA NUMERIC OPTIONS(description = "")
  , DEBE_HABER STRING OPTIONS(description = "")
  , MONEDA_2 STRING OPTIONS(description = "")
  , MONEDA_3 STRING OPTIONS(description = "")
  , TEXTO STRING OPTIONS(description = "")
  , PORCENTAJE NUMERIC OPTIONS(description = "")
  , PAIS STRING OPTIONS(description = "")
  , IDIOMA STRING OPTIONS(description = "")
);

INSERT INTO `datalake-vanti.integracion_suplos.certificados` (SOCIEDAD, CONTADOR, POS_BET, 0GL_ACCOUNT, 0CHRT_ACCTS, 0COMP_CODE, ZBANCPAG, ZIND_ICA, ZIND_IVA, ZFEC_EXP, ZCIU_EXPE, ZCUENTA, ZIDEMPRESA, ZCIU_PAGO, TEXTOS, NOTAS, VALOR, ART_DEC, ZXREF2, RESOLUCION, DOCUMENTO, EJERCICIO, PERIODO, POSICION, TIPO_RETENCION, IND_RETENCION, BASE, IMP_RETENCION, IMP_EXEN_IMP, 0VENDOR, XREF1, XREF3, CLASE_DOCUMENTO, FECHA_DOC, FECHA_CONT, MONEDA_LOCAL, VALOR_MONEDA, DEBE_HABER, MONEDA_2, MONEDA_3, TEXTO, PORCENTAJE, PAIS, IDIOMA)
SELECT 
  NULLIF(W.BUKRS, "")
  , W.BELNR
  , NULLIF(W.HKONT, "")
  , NULLIF(BS.XREF2, "")
  , W.GJAHR
  , BS.H_MONAT
  , W.BUZEI
  , NULLIF(W.WITHT, "")
  , NULLIF(W.WT_WITHCD, "")
  , FW.WT_QSSHH
  , W.WT_QBSHH
  , W.WT_QSFHH
  , NULLIF(BU.BU_SORT1, "")
  , CASE
      WHEN BU.TYPE = '1' THEN CONCAT(BU.NAME_LAST, '', BU.NAME_LAST2, '', BU.NAME_FIRST, BU.NAMEMIDDLE)
      WHEN BU.TYPE = '2' THEN CONCAT(BU.NAME_ORG1, '', BU.NAME_ORG2, '', BU.NAME_ORG3, '', BU.NAME_ORG4)
      ELSE CONCAT(BU.NAME_GRP1, '', BU.NAME_GRP2)
    END 
  , NULLIF(BS.H_BLART, "")
  , BS.H_BLDAT
  , BS.H_BUDAT
  , NULLIF(BS.PSWSL, "")
  , BS.DMBTR
  , NULLIF(BS.SHKZG, "")
  , NULLIF(T.WAERS, "")
  , NULLIF(BK.WAERS, "")
  , NULLIF(TU.TEXT40, "")
  , TZ.QSATZ
  , NULLIF(TT.LAND1, "")
  , NULLIF(TT.SPRAS, "")
FROM
  `qa_raw_sap.with_item` W 
JOIN
  `qa_raw_sap.bseg` BS
  ON W.BELNR = BS.BELNR
  AND W.MANDT = BS.MANDT
  AND W.HKONT = BS.HKONT
  AND W.BUKRS = BS.BUKRS
  AND W.GJAHR = BS.GJAHR
JOIN
  `qa_raw_sap.t001` T
  ON W.BUKRS = T.BUKRS
  AND W.MANDT = T.MANDT
JOIN
  `qa_raw_sap.bkpf` BK
  ON W.BELNR = BK.BELNR
  AND W.BUKRS = BK.BUKRS
  AND W.MANDT = BK.MANDT
  AND W.GJAHR = BK.GJAHR
JOIN `qa_raw_sap.t059z` TZ
  ON W.WITHT = TZ.WITHT
  AND W.WT_WITHCD = TZ.WT_WITHCD
  AND W.MANDT = TZ.MANDT
JOIN `qa_raw_sap.t059zt` TT
  ON W.WITHT = TT.WITHT
  AND W.WT_WITHCD = TT.WT_WITHCD
  AND W.MANDT = TT.MANDT
JOIN `qa_raw_sap.t059u` TU
  ON W.WITHT = TU.WITHT
  AND W.MANDT = TU.MANDT
JOIN `qa_raw_sap.but000` BU
  ON W.WT_ACCO = BU.PARTNER
  AND W.MANDT = BU.CLIENT
WHERE (DATE(BLDAT) < DATE('1900-01-01') OR DATE(BLDAT) > DATE('2100-01-01'))
AND (DATE(BUDAT) < DATE('1900-01-01') OR DATE(BUDAT) > DATE('2100-01-01'));

